const $=s=>document.querySelector(s);const fmt=n=>n<0?'−'+Math.abs(n):String(n);const operand=n=>n<0?'('+fmt(n)+')':fmt(n);const calc=(a,o,b)=>o==='+'?a+b:o==='-'?a-b:o==='*'?a*b:a/b;const symbol=o=>({'+':'＋','-':'−','*':'×','/':'÷'})[o];
const banks=[[[ -3,'+',2,'*',4],[5,'-',-2,'*',3],[-6,'+',3,'*',-4],[7,'-',2,'*',5],[2,'+',-3,'*',2],[-8,'-',-2,'*',4]], [[-4,'*',2,'+',7],[8,'/',-2,'-',3],[-12,'/',3,'+',5],[3,'*',-4,'-',2],[18,'/',-3,'+',4],[-2,'*',-5,'-',6]], [[12,'/',-3,'+',2,'*',5],[-3,'+',-2,'*',4],[8,'/',-2,'-',3,'*',2],[-6,'*',2,'+',12,'/',-3],[4,'*',-2,'-',9,'/',3],[18,'/',-3,'+',-2,'*',3]]];
let step=1,example=0,phase='select',tokens=[],selected=-1,history=[],level=3,good=0,bad=0,zero=0,records=[],record=null,finished=false,hint=false,transition='initial',notice='',done=false;const examples=[[-3,'+',-2,'*',4],[8,'/',-2,'-',3],[12,'/',-3,'+',2,'*',5]];
function eligible(t){const high=[];for(let i=1;i<t.length;i+=2)if(t[i]==='*'||t[i]==='/')high.push(i);return high.length?[high[0]]:t.length>1?[1]:[]}
function expression(t,mark=-1,buttons=false){return '<div class="equation">'+t.map((v,i)=>i%2?`<${buttons?'button':'span'} ${buttons?`data-op="${i}" aria-label="${operand(t[i-1])} ${symbol(v)} ${operand(t[i+1])} を計算する"`:''} class="${i===mark?'chosen':''}">${symbol(v)}</${buttons?'button':'span'}>`:`<span>${i===0?fmt(v):operand(v)}</span>`).join('')+'</div>'}
function highlighted(t,i,buttons=false){return '<div class="equation">'+t.map((v,j)=>{let s=j%2?(buttons?`<button data-op="${j}" aria-label="${operand(t[j-1])} ${symbol(v)} ${operand(t[j+1])} を計算する">${symbol(v)}</button>`:symbol(v)):j===0?fmt(v):operand(v);return (j===i-1?'<span class="marked">':'')+s+(j===i+1?'</span>':' ')}).join('')+'</div>'}
function startExample(){tokens=[...examples[example]];history=[];selected=-1;phase='demo';done=false;render()}
function startQuestion(){const d=$('#difficulty').value;const tier=d==='auto'?Math.min(2,Math.floor(records.length/4)):Number(d);const bank=banks[tier];tokens=[...bank[records.length%bank.length]];history=[];selected=-1;phase='select';hint=false;done=false;record={problem:tokens.map((v,i)=>i%2?symbol(v):operand(v)).join(' '),difficulty:tier,supportLevel:level,hintUsed:false,afterChange:transition,attempts:[],correct:true,answerCount:0};render()}
function nav(){ $('#steps').innerHTML=['ゴール','一緒に解く','自分で解く'].map((t,i)=>`<button data-step="${i+1}" class="${step===i+1?'active':''}" ${step===i+1?'aria-current="step"':''}>${i+1} ${t}</button>`).join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n===3&&step===3)return;step=n;notice='';if(n===2)startExample();else if(n===3){finished=false;startQuestion()}else render()})}
function render(){nav();$('#support').value=level;const s=$('#surface');if(step===1){s.innerHTML=`<div class="eyebrow">STEP 1</div><h2>今日のゴール</h2>${expression([-3,'+',-2,'*',4])}<p class="prompt">どこを先に計算するか、自分で考えて解ける。</p><div class="actions"><button class="primary" id="begin">一緒に解いてみる</button></div>`;$('#begin').onclick=()=>{step=2;example=0;startExample()};return}
if(step===2){if(phase==='rule'){s.innerHTML='<div class="eyebrow">STEP 2 · まとめ</div><h2>一部分ずつ、簡単な式にする</h2><div class="rule"><span>×・÷</span><span>→</span><span>＋・−</span></div><p class="prompt">同じ優先順位の計算は、左から。<br>かっこ内に計算があるときは、その中が先。</p><p class="small">（−2）のかっこは、負の数を表しています。中に計算はありません。</p><div class="actions"><button id="again">もう一度見る</button><button class="primary" id="practice">自分で解いてみる</button></div>';$('#again').onclick=()=>{example=0;startExample()};$('#practice').onclick=()=>{step=3;startQuestion()};return}const i=eligible(tokens)[0];s.innerHTML=`<div class="topline"><span class="eyebrow">STEP 2 · 例 ${example+1} / 3</span><span class="badge">一緒に解く</span></div><h2>${tokens.length===1?'式がひとつの数になった':'まず、この部分を計算しよう'}</h2><div class="history">${history.map(h=>highlighted(h.tokens,h.op)).join('')}</div><div class="replace">${tokens.length>1?highlighted(tokens,i):expression(tokens)}</div><p class="prompt">${tokens.length>1?(tokens[i]==='*'||tokens[i]==='/'?'×・÷の部分を、ひとつの数に置き換える。':'残った＋・−を計算する。'):'答えは '+fmt(tokens[0])+'。'}</p><div class="actions"><button class="primary" id="demo">${tokens.length>1?'囲んだ部分を計算する':example<2?'次の例を見る':'順序をまとめる'}</button></div>`;$('#demo').onclick=()=>{if(tokens.length>1){history.push({tokens:[...tokens],op:i});tokens.splice(i-1,3,calc(tokens[i-1],tokens[i],tokens[i+1]));render()}else if(example<2){example++;startExample()}else{phase='rule';render()}};return}
if(finished){s.innerHTML=`<div class="eyebrow">STEP 3 · ふりかえり</div><h2>${zero>=2?'支援なしで、自分で解けました':'今日はここまで'}</h2><p>${records.length}問に取り組みました。${zero>=2?'最後の2問は、支援なしで初回正解できました。':'必要な支援を確認しながら、また取り組みましょう。'}</p><div class="actions"><button id="restart">もう一度取り組む</button><button id="review">一緒に解くへ戻る</button></div>`;$('#restart').onclick=()=>{records=[];level=3;good=bad=zero=0;transition='initial';finished=false;startQuestion()};$('#review').onclick=()=>{step=2;example=0;startExample()};updateRecords();return}
const first=eligible(tokens)[0];const show=level===3||hint;let prompt=done?'この問題を解けました。':phase==='input'?'選んだ部分の計算結果を入力しよう。':show?'囲んだ部分の記号を押して、計算しよう。':level===2?'×・÷はあるかな？ なければ左から。':'次に計算する記号を選ぼう。';s.innerHTML=`<div class="topline"><span class="eyebrow">STEP 3 · ${records.length+1}問目</span><span class="badge">${['支援なし','支援少なめ','支援中程度','支援多め'][level]}</span></div><h2>一部分ずつ、解いてみよう</h2>${history.length?'<div class="history">'+history.map(h=>show?highlighted(h.tokens,h.op):expression(h.tokens)).join('')+'</div>':''}<div class="replace">${show&&!done&&phase==='select'?highlighted(tokens,first,true):expression(tokens,selected,!done&&phase==='select')}</div><p class="prompt">${prompt}</p><div class="actions">${phase==='input'&&!done?'<form id="answerForm"><label for="answer" class="small">計算結果 </label><input class="answer" id="answer" autocomplete="off" inputmode="text" placeholder="例：−8"><button class="primary">確かめる</button></form>':''}${level===1&&!hint&&!done?'<button id="hint">ヒント</button>':''}${done?'<button class="primary" id="next">次へ</button>':''}</div><p class="feedback" role="status">${notice}</p>`;s.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>choose(+b.dataset.op));if($('#answerForm')){$('#answerForm').onsubmit=e=>{e.preventDefault();answer()};$('#answer').focus()}if($('#hint'))$('#hint').onclick=()=>{hint=true;record.hintUsed=true;render()};if($('#next'))$('#next').onclick=advance}
function log(type,value,correct){record.answerCount++;record.attempts.push({type,value,correct,supportLevel:level,time:new Date().toISOString()});if(!correct)record.correct=false}
function choose(i){const ok=eligible(tokens).includes(i);log('order',i,ok);if(!ok){notice='順番をもう一度確かめよう。';render();return}selected=i;phase='input';notice='';render()}
function answer(){const raw=$('#answer').value.trim().replace(/[−ー－]/g,'-').replace(/[＋]/g,'+').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-65248));if(!/^[+-]?\d+$/.test(raw)){notice='整数を入力しよう。マイナスは「-」でも入力できます。';$('.feedback').textContent=notice;return}const value=Number(raw),target=calc(tokens[selected-1],tokens[selected],tokens[selected+1]);const ok=value===target;log('calculation',value,ok);if(!ok){notice='符号と数を、もう一度確かめよう。';$('.feedback').textContent=notice;return}history.push({tokens:[...tokens],op:selected});tokens.splice(selected-1,3,value);selected=-1;phase='select';notice='この部分を置き換えました。';if(tokens.length===1){done=true;notice='順番に計算できました。'}render()}
function adjust(r){const stable=r.correct&&!r.hintUsed;zero=stable&&level===0?zero+1:0;if(stable){good++;bad=0}else{bad++;good=0}let next=level;transition='maintained';if(good>=2&&level>0){next--;good=bad=0;transition='reduced'}else if(bad>=2&&level<3){next++;good=bad=0;transition='restored'}level=next;return stable}
function advance(){records.push(record);adjust(record);updateRecords();const min=Math.max(1,Number($('#min').value)||8),max=Math.max(min,Number($('#max').value)||24);if((records.length>=min&&zero>=2)||records.length>=max){finished=true;render()}else{notice=transition==='reduced'?'少し手がかりを減らして、試してみよう。':transition==='restored'?'手がかりを増やして、もう一度取り組もう。':'';startQuestion()}}
function updateRecords(){$('#records').innerHTML=records.length?'<table><thead><tr><th>問題</th><th>支援</th><th>初回正解</th><th>ヒント</th><th>回答回数</th><th>変更後</th></tr></thead><tbody>'+records.map(r=>`<tr><td>${r.problem}</td><td>${r.supportLevel}</td><td>${r.correct?'○':'再確認'}</td><td>${r.hintUsed?'あり':'なし'}</td><td>${r.answerCount}</td><td>${{reduced:'支援を減らした後',restored:'支援を戻した後',maintained:'維持',initial:'開始',manual:'手動'}[r.afterChange]}</td></tr>`).join('')+'</tbody></table>':'まだ完了した問題はありません。'}
$('#settings').onclick=()=>{$('#teacher').open=!$('#teacher').open;if($('#teacher').open)$('#teacher').scrollIntoView({behavior:'smooth'})};$('#support').onchange=()=>{level=Number($('#support').value);good=bad=zero=0;transition='manual';if(step===3&&!finished){record.correct=false;record.attempts.push({type:'supportChange',value:level});render()}};$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({settings:{min:$('#min').value,max:$('#max').value,difficulty:$('#difficulty').value},records,current:done?null:record},null,2)],{type:'application/json'}));a.download='math006-learning-record.json';a.click();URL.revokeObjectURL(a.href)};render();updateRecords();
