// Fixed branching routes: fade after clean success; restore support at the point of difficulty.
let formulaSupport=4, notationSupport=4, formulaDone=false, formulaValue='', finalValue='', formulaMessage='', finalMessage='', usedFormulaHelp=false, usedNotationHelp=false, formulaMistake=false, notationMistake=false, counted=false;
let routeLevel=4, routeMessage='', nextRouteLevel=4;
const independent=Array.from({length:7},()=>new Set());
const labels=['なし','短いヒント','対応を見る','関係を見る','一緒に解く'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function unlocked(){return independent[topic].size>=2}
const oldQuestion=question;
question=function(){if(step===0)return oldQuestion();const v=['x','y','a','b','p','m'][variant%6],w=['z','b','c','d','q','n'][variant%6],n=[4,6,3,7,2,5][variant%6];let t={...topics[topic]};
if(topic===0)t={...t,problem:`1個${v}円のお菓子を${n}個買います。代金を式で表そう。`,meaning:`${v}は1個の値段`,reason:'1個の値段 × 個数',raw:`${v} × ${n}`,ans:`${n}${v}`,calc:[`${v} × ${n}`,`${v} ＋ ${n}`,`${v} ÷ ${n}`],parts:[v,String(n)],op:'×',diagram:[['1個の値段',`${v}円`],['個数',`${n}個`]]};
if(topic===1)t={...t,problem:`1冊${v}円のノートを${w}冊買います。代金を式で表そう。`,meaning:`${v}は1冊の値段、${w}は冊数`,reason:'1冊の値段 × 冊数',raw:`${v} × ${w}`,ans:`${v}${w}`,calc:[`${v} × ${w}`,`${v} ＋ ${w}`,`${v} ÷ ${w}`],parts:[v,w],op:'×',diagram:[['1冊の値段',`${v}円`],['冊数',`${w}冊`]]};
if(topic===2)t={...t,problem:`1辺が${v} cmの正方形です。面積を式で表そう。`,meaning:`${v}は1辺の長さ`,reason:'たて × よこ',raw:`${v} × ${v}`,ans:`${v}²`,calc:[`${v} × ${v}`,`${v} ＋ ${v}`,`${v} × 2`],parts:[v,v],op:'×',diagram:[['たて',`${v} cm`],['よこ',`${v} cm`]]};
if(topic===3)t={...t,problem:`1袋${v} gの袋が1袋あります。重さを式で表そう。`,meaning:`${v}は1袋の重さ`,reason:'1袋の重さ × 袋の数',raw:`${v} × 1`,ans:v,calc:[`${v} × 1`,`${v} ＋ 1`,`${v} ÷ 1`],parts:[v,'1'],op:'×',diagram:[['1袋の重さ',`${v} g`],['袋の数','1袋']]};
if(topic===4)t={...t,problem:`数直線の位置${v}を、0に対して反対側にうつします。−1をかける式を書こう。`,meaning:`${v}は、もとの位置`,reason:'もとの位置 × (−1)',raw:`${v} × (−1)`,ans:`−${v}`,calc:[`${v} × (−1)`,`${v} ＋ (−1)`,`${v} × 1`],parts:[v,'(−1)'],op:'×',diagram:[['もとの位置',v],['反対側へ','−1倍']]};
if(topic===5)t={...t,problem:`${v} cmのひもを${n}等分します。1本の長さを式で表そう。`,meaning:`${v}はひも全体の長さ`,reason:'全体の長さ ÷ 分ける数',raw:`${v} ÷ ${n}`,ans:`${v}/${n}`,calc:[`${v} ÷ ${n}`,`${n} ÷ ${v}`,`${v} × ${n}`],parts:[v,String(n)],op:'÷',diagram:[['全体の長さ',`${v} cm`],['分ける数',String(n)]]};
if(topic===6)t={...t,problem:`${v} Lのジュースを${w}人で等しく分けます。1人分の量を式で表そう。（${w}は正の整数）`,meaning:`${v}は全体の量、${w}は人数`,reason:'全体の量 ÷ 人数',raw:`${v} ÷ ${w}`,ans:`${v}/${w}`,calc:[`${v} ÷ ${w}`,`${w} ÷ ${v}`,`${v} × ${w}`],parts:[v,w],op:'÷',diagram:[['全体の量',`${v} L`],['人数',`${w}人`]]};
t.key=`${topic}:${variant%6}`;t.hints=topic<2?['文字を使うかけ算の×は、書かなくてOK。','数字を前に書こう。',`${t.raw} = ${t.ans}`]:topic===2?['同じ文字を、何回かけている？','2回かけたら、右上に小さく2。',`${t.raw} = ${t.ans}`]:topic===3?['1をかけても、同じ重さ。','文字の前の1は、書かなくてOK。',`${t.raw} = ${t.ans}`]:topic===4?['−1をかけると、符号が反対。','1は消して、−は残そう。',`${t.raw} = ${t.ans}`]:['割られる数と、割る数はどれ？','÷の前が上、後ろが下。',`${t.raw} = ${answerHTML(t)}`];return t;};
const oldReset=reset;
reset=function(){oldReset();formulaDone=false;formulaValue='';finalValue='';formulaMessage='';finalMessage='';usedFormulaHelp=false;usedNotationHelp=false;formulaMistake=false;notationMistake=false;counted=false;};
setStep=function(s){if(s===2&&!unlocked()){msg='別の2問を、支援なしで解いてから進もう。';render();return}if(s===2&&step!==2)variant++;step=s;reset();render();};
setTopic=function(t){topic=+t;variant=0;routeLevel=4;nextRouteLevel=4;routeMessage='';formulaSupport=notationSupport=4;if(step===2&&!unlocked())step=1;reset();render();};
function restoreAt(track){routeLevel=Math.min(4,routeLevel+1);if(track==='formula')formulaSupport=Math.max(formulaSupport,routeLevel);else notationSupport=Math.max(notationSupport,routeLevel);routeMessage=track==='formula'?'数量の関係を、もう一度見てみよう。':'立てた式はそのまま。書き方のヒントを見よう。';}
function rememberInput(track,value){if(track==='formula')formulaValue=value;else finalValue=value;}
function supportBox(track){const s=track==='formula'?formulaSupport:notationSupport;if(track==='formula'){if(s>=2){usedFormulaHelp=true;return `<div class="hint">${s>=3?`<div class="quantity">${q.diagram.map(([a,b])=>`<div class="unit"><small>${a}</small><div>${b}</div></div>`).join('')}</div><p>${q.reason}</p>`:`<p>${q.meaning}</p>`}</div>`}if(s===1){usedFormulaHelp=true;return '<p class="muted">文字は何の数？ かける？ 割る？</p>'}return '';}if(s>=2){usedNotationHelp=true;return `<div class="hint">${s>=3?q.hints[1]:q.hints[0]}</div>`}if(s===1){usedNotationHelp=true;return '<p class="muted">×や÷を使わずに書こう。</p>'}return '';}
function formulaUI(){if(formulaSupport===4){usedFormulaHelp=true;return `<p>どの計算かな？</p><div class="chips">${q.calc.map((c,i)=>`<button type="button" onclick="submitFormula(${i})">${c}</button>`).join('')}</div>`}return `<form onsubmit="event.preventDefault();submitFormula(this.elements.formula.value)"><label>式 <input name="formula" aria-label="立式の答え" value="${esc(formulaValue)}" oninput="rememberInput('formula',this.value)" autocomplete="off" placeholder="式を入力"></label> <button class="primary">確かめる</button><small class="entry-note">×は *、÷は / でも入力できます。</small></form>`;}
function notationUI(){if(notationSupport===4){usedNotationHelp=true;let p=topic===0?`<input name="piece" aria-label="数字の穴埋め" inputmode="numeric" placeholder="□" class="piece">${q.parts[0]}`:topic===1?`${q.parts[0]}<input name="piece" aria-label="文字の穴埋め" placeholder="□" class="piece">`:topic===2?`${q.parts[0]}<sup><input name="piece" aria-label="指数の穴埋め" inputmode="numeric" placeholder="□" class="piece"></sup>`:topic>=5?`<span class="frac"><span>${q.parts[0]}</span><span><input name="piece" aria-label="分母の穴埋め" placeholder="□" class="piece"></span></span>`:topic===4?`<input name="piece" aria-label="符号の穴埋め" placeholder="□" class="piece">${q.parts[0]}`:`<input name="piece" aria-label="文字の穴埋め" placeholder="□" class="piece">`;return `<form onsubmit="event.preventDefault();submitPiece(this.elements.piece.value)"><div class="row"><span class="math">${p}</span><button class="primary">確かめる</button></div></form>`}return `<form onsubmit="event.preventDefault();check(this.elements.answer.value)"><label>文字式 <input name="answer" aria-label="文字式の答え" value="${esc(finalValue)}" oninput="rememberInput('notation',this.value)" autocomplete="off" placeholder="答えを入力"></label> <button class="primary">確かめる</button>${topic>=5?'<small class="entry-note">分数は「上/下」で入力できます。</small>':topic===2?'<small class="entry-note">右上の2は ^2 でも入力できます。</small>':''}</form>`;}
function rawNorm(s){return norm(s).replace(/[()（）]/g,'').replace(/\//g,'÷').replace(/x(?=[0-9])/g,'x');}
function validFormula(v){const a=rawNorm(v),want=rawNorm(q.raw);if(a===want)return true;if(q.op==='×')return a===rawNorm(`${q.parts[1]} × ${q.parts[0]}`);return false;}
function submitFormula(v){if(solved)return;const value=typeof v==='number'?q.calc[v]:v;formulaValue=value;if(!value.trim()){formulaMessage='式を入力してみよう。';render();return}if(validFormula(value)){formulaDone=true;formulaMessage='この式で合っています。';}else{formulaMistake=true;independent[topic].clear();restoreAt('formula');formulaMessage='もう一度、式を作ってみよう。';}render();}
function submitPiece(v){let a=topic===0?v+q.parts[0]:topic===1?q.parts[0]+v:topic===2?q.parts[0]+'^'+v:topic>=5?q.parts[0]+'/'+v:topic===4?v+q.parts[0]:v;check(a);}
check=function(v){if(!formulaDone||solved)return;finalValue=v;if(!v.trim()){finalMessage='答えを入力してみよう。';render();return}if(norm(v)===norm(q.ans)){solved=true;finalMessage='この書き方で合っています。';if(!counted){const clean=!formulaMistake&&!notationMistake;if(formulaSupport===0&&notationSupport===0&&!usedFormulaHelp&&!usedNotationHelp&&clean)independent[topic].add(q.key);nextRouteLevel=clean?Math.max(0,routeLevel-1):routeLevel;counted=true;routeMessage=unlocked()?'別の2問を、支援なしで解けました。':clean&&routeLevel>0?'次は、ヒントを少し減らしてみよう。':clean?'別の問題でも、自分で解いてみよう。':'次は、今のヒントで別の問題を解こう。';}}else{notationMistake=true;independent[topic].clear();restoreAt('notation');finalMessage='もう一度、書き直してみよう。';}render();};
nextPractice=function(){if(!solved)return;routeLevel=nextRouteLevel;formulaSupport=notationSupport=routeLevel;variant++;routeMessage='';reset();render();};
function practiceHTML(){let h=`<section class="card"><div class="row spread"><h2>Web上で解く</h2><span class="muted">${labels[routeLevel]}</span></div><p>${q.problem}</p><div class="stageflow"><section class="learning-stage ${formulaDone?'past-stage':'current-stage'}"><h3>① どんな計算になる？</h3>${formulaDone?`<div class="math">${esc(formulaValue)}</div><button type="button" onclick="formulaDone=false;solved=false;render()">式を見直す</button>`:supportBox('formula')+formulaUI()}<div class="feedback" role="status">${formulaMessage}</div></section>${formulaDone?`<section class="learning-stage ${solved?'past-stage':'current-stage'}"><h3>② 式を短く書こう</h3>${solved?`<div class="math">${answerHTML(q)}</div>`:supportBox('notation')+notationUI()}<div class="feedback" role="status">${finalMessage}</div></section>`:''}</div>${solved?`<div class="answer"><div class="math">${esc(formulaValue)} ＝ ${answerHTML(q)}</div><p>${independent[topic].has(q.key)?'支援なしで解けました。':'支援を使って解けました。次は必要な支援だけ残そう。'}</p><div class="row"><button class="primary" onclick="nextPractice()">別の問題を解く</button>${unlocked()?'<button onclick="setStep(2)">ノートで解く</button>':''}</div></div>`:''}<p class="muted">${routeMessage || '解き方に合わせて、ヒントが変わります。'}</p><p class="muted">支援なしで解けた別の問題：${independent[topic].size} / 2<br>${unlocked()?'この内容は、ノートへ進めます。':'立式と書き方の両方を、支援なしで確かめよう。'}</p></section>`;return h;}
function nextNotebook(){variant++;reset();render();}
function notebookHTML(){const hints=[`${q.meaning}。<br>${q.reason}`,q.hints[1],`<span class="math">${esc(q.raw)} ＝ ${answerHTML(q)}</span>`];return `<div class="row spread"><span class="label">STEP 3</span><label>学ぶ内容 <select onchange="setTopic(this.value)">${topics.map((t,i)=>`<option value="${i}" ${topic===i?'selected':''}>${t.name}</option>`).join('')}</select></label></div><section class="card"><h2>ノートで自分で解く</h2><p class="muted">問題を写す → 式を作る → 式を短く書く</p><p class="notebook-problem">${q.problem}</p><div class="row"><button onclick="hint=Math.min(3,hint+1);render()" ${hint===3?'disabled':''}>ヒントを見る${hint?'（'+Math.min(3,hint+1)+'）':''}</button><button onclick="reveal=!reveal;render()">${reveal?'答えを隠す':'答え合わせ'}</button></div>${hints.slice(0,hint).map((h,i)=>`<div class="hint"><strong>ヒント${i+1}</strong><div>${h}</div></div>`).join('')}${reveal?`<div class="answer"><p>${q.reason}</p><div class="math">${esc(q.raw)} ＝ ${answerHTML(q)}</div><small>ノートに書いた式と見くらべよう。</small></div>`:''}</section><button class="primary" onclick="nextNotebook()">次の問題</button>`;}
const baseRender=render;
render=function(){if(step===2&&!unlocked())step=1;if(step===1){document.querySelector('#app').innerHTML=`<div class="row spread"><span class="label">STEP 2</span><label>学ぶ内容 <select onchange="setTopic(this.value)">${topics.map((t,i)=>`<option value="${i}" ${i===topic?'selected':''}>${t.name}</option>`).join('')}</select></label></div>${practiceHTML()}`;}else if(step===2){document.querySelector('#app').innerHTML=notebookHTML();}else baseRender();document.querySelector('#nav').innerHTML=['解き方を見る','Web上で解く','ノートで自分で解く'].map((s,i)=>`<button class="${step===i?'active':''}" onclick="setStep(${i})" ${i===2&&!unlocked()?'disabled title="別の2問を支援なしで解いてから進みます"':''}>STEP${i+1}　${s}</button>`).join('');};
topics[0].hints=['数字と文字の間の×は、書かなくてOK。','数字を前に書こう。','a × 5 = 5 × a = 5a'];
topics[1].hints=['文字どうしの×も、書かなくてOK。','文字をつなげて書こう。','a × b = ab'];
topics[2].hints=['同じaを、何回かけている？','2回かけたら、右上に小さく2。','a × a = a²（2aはaを2個足す式）'];
topics[3].hints=['1をかけても、同じ重さ。','文字の前の1は、書かなくてOK。','1 × a = a'];
topics[4].hints=['−1をかけると、符号が反対。','1は消して、−は残そう。','(−1) × a = −a'];
for(let t=5;t<7;t++)topics[t].hints[1]='÷の前が上、後ろが下。';
reset();render();
